# Generated by Django 5.1.6 on 2025-04-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออุปกรณ์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='จำนวนทั้งหมด')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
            ],
            options={
                'verbose_name': 'อุปกรณ์',
                'verbose_name_plural': 'อุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อผู้ใช้งาน')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
                'verbose_name_plural': 'ผู้ใช้งาน',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยืม')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืน')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดคืน')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวนที่ยืม')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.equipment', verbose_name='อุปกรณ์')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.user', verbose_name='ผู้ยืม')),
            ],
            options={
                'verbose_name': 'รายการยืม',
                'verbose_name_plural': 'รายการยืม',
            },
        ),
    ]
